# Generated by Django 4.2.4 on 2023-08-21 14:06

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 15, 6, 53, 707832)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
