# Generated by Django 4.2.4 on 2023-08-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='date_created',
        ),
    ]
